import './globals.css'

import { Inter } from 'next/font/google'
import { cookies } from 'next/headers';

import { Copyright } from '@/components/Copyright';
import { EmpytMemories } from '@/components/EmpytMemories';
import { SignIn } from '@/components/SignIn';
import { Hero } from '@/components/hero';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const IsAuthen = cookies().has('Token');

  return (

    <html lang="en">
      <body className={`${inter.className} bg-gray-900 font-sans text-gray-100`}>
      
        <main className="grid min-h-screen grid-cols-2">
          {/* Left */}
          <div className="relative flex flex-col items-start justify-between overflow-hidden border-r border-white/10 bg-[url(../assets/bg_stars.svg)] bg-cover px-28 py-16">
            {/* Blur */}
            <div className="absolute right-0 top-1/2 h-[288px] w-[526px] -translate-y-1/2 translate-x-1/2 rounded-full bg-purple-700 opacity-50 blur-full" />

            {/* Stripes */}
            <div className="absolute bottom-0 right-2 top-0 w-2 bg-stripes" />

            {/* Sign In */}
            {IsAuthen ? <p>oi</p> : <SignIn />}

            {/* Hero */}
            <Hero />

            {/* Copyright */}
            <Copyright />   
          </div>

          {/* Right */}
          <div className="flex flex-col bg-[url(../assets/bg_stars.svg)] bg-cover p-16">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
